import React, { useState, useRef, useEffect } from 'react';
import {
  View,
  Text,
  StyleSheet,
  TextInput,
  ScrollView,
  Dimensions,
  TouchableOpacity,
  Platform,
} from 'react-native';

export const style = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F9FAFB',
    fontFamily: 'InstrumentSerif'
  },
  background: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    height: 300,
    backgroundColor: '#FFFFFF',
  },
  dateContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    fontFamily: 'serif',
    paddingBottom: 40,
    backgroundColor: '#FFFFFF',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -2 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 3,
    height: '100%',
  },
  header: {
    justifyContent: 'center',
    alignItems: 'center',
    padding: 24,
    width: '100%',
  },
  dateText: {
    color: '#1F2937',
    fontSize: 32,
    fontWeight: '600',
    marginBottom: 24,
    fontFamily: 'InstrumentSerif',
    letterSpacing: -0.5,
    textAlign: 'center',
  },
  inputContainer: {
    width: '92%',
    height: '80%',
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    padding: 20,
    color: '#1F2937',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 4,
    transform: [{ translateY: 0 }],
  },
  textInput: {
    color: '#1F2937',
    fontSize: 20,
    height: '100%',
    width: '100%',
    borderRadius: 16,
    textAlignVertical: 'top',
    backgroundColor: 'transparent',
    fontFamily: 'InstrumentSerif',
    padding: 0,
    lineHeight: 32,
  },
  weekIndicator: {
    position: 'absolute',
    bottom: 16,
    width: '100%',
    textAlign: 'center',
    fontSize: 18,
    color: '#1F2937',
    fontFamily: 'InstrumentSerif',
    backgroundColor: '#FFFFFF',
    paddingVertical: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -4 },
    shadowOpacity: 0.04,
    shadowRadius: 8,
    elevation: 2,
  },
  bodergrad: {
    flex: 1,
    justifyContent: 'center',
    borderRadius: 20,
    padding: 10,
    width: '100%',
    height: '100%',
    backgroundColor: '#FFFFFF',
    color: '#1F2937',
  },
  promptText: {
    color: '#777',
    fontSize: 20,
    fontFamily: 'InstrumentSerif',
  },
  message: {
    color: '#1F2937',
    fontSize: 20,
    height: '100%',
    width: '100%',
    borderRadius: 16,
    textAlignVertical: 'top',
    backgroundColor: 'transparent',
    fontFamily: 'InstrumentSerif',
    padding: 16,
    lineHeight: 28
  },
  weekContainer: {
    height: Dimensions.get('window').height,
    width: '100%',
    backgroundColor: '#FFFFFF',
  },
  weekNavigation: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 16,
  },
  weekNumberText: {
    fontSize: 18,
    fontWeight: 'bold',
  },
  dayContainer: {
    width: 40,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#ccc',
    borderRadius: 20,
  },
  dayText: {
    fontSize: 16,
  },
});